export const FORUMLIST_REPLACE = 'FORUMLIST_REPLACE'
export const FORUMLIST_ADD_FORUM = 'FORUMLIST_ADD_FORUM'

export const APPCONTROL_SET_ACTIVE_POSTING_FORUM = 'APPCONTROL_SET_ACTIVE_POSTING_FORUM'

export const ADD_POST_FAVORITES = 'ADD_POST_FAVORITES'
export const ADD_POST_FAVORITES_BATCH = 'ADD_POST_FAVORITES_BATCH'
export const ADD_POST_STREAM = 'ADD_POST_STREAM'
export const ADD_POST_STREAM_BATCH = 'ADD_POST_STREAM_BATCH'
export const ADD_THREAD_COMMENT = 'ADD_THREAD_COMMENT'


export const KRETS_ADD_PERSON_BATCH = 'KRETS_ADD_PERSON_BATCH'

export const MESSAGE_RECIPIENTS_ADD_PERSON = 'MESSAGE_RECIPIENTS_ADD_PERSON'
export const MESSAGE_RECIPIENTS_REMOVE_PERSON = 'MESSAGE_RECIPIENTS_REMOVE_PERSON'
export const MESSAGE_RECIPIENTS_CLEAR = 'MESSAGE_RECIPIENTS_CLEAR'
export const MESSAGE_CONVERSATION_ADD = 'MESSAGE_CONVERSATION_ADD'
export const MESSAGE_CONVERSATON_ADD_BATCH = 'MESSAGE_CONVERSATON_ADD_BATCH'

export const APPCONTROL_USER_LOGIN = 'APPCONTROL_USER_LOGIN'

export const FORUMPOST_COMMENT_ADD = 'FORUMPOST_COMMENT_ADD'

export const USERS_ADD_USER_BATCH = 'USERS_ADD_USER_BATCH'


