export const FORUMLIST_REPLACE = 'FORUMLIST_REPLACE'
export const FORUMLIST_ADD_FORUM = 'FORUMLIST_ADD_FORUM'

export const ADD_POST_FAVORITES = 'ADD_POST_FAVORITES'
export const ADD_POST_STREAM = 'ADD_POST_STREAM'
export const ADD_THREAD_COMMENT = 'ADD_THREAD_COMMENT'

export const KRETS_ADD_PERSON = 'KRETS_ADD_PERSON'

export const MESSAGE_RECIPIENTS_ADD_PERSON = 'MESSAGE_RECIPIENTS_ADD_PERSON'
export const MESSAGE_RECIPIENTS_REMOVE_PERSON = 'MESSAGE_RECIPIENTS_REMOVE_PERSON'
export const MESSAGE_RECIPIENTS_CLEAR = 'MESSAGE_RECIPIENTS_CLEAR'

export const APPCONTROL_USER_LOGIN = 'APPCONTROL_USER_LOGIN'